[2024-05-21T04:52:55.589+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-21T04:52:55.596+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.push_to_s3 manual__2024-05-21T04:52:48.278946+00:00 [queued]>
[2024-05-21T04:52:55.599+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.push_to_s3 manual__2024-05-21T04:52:48.278946+00:00 [queued]>
[2024-05-21T04:52:55.599+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-05-21T04:52:55.605+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): push_to_s3> on 2024-05-21 04:52:48.278946+00:00
[2024-05-21T04:52:55.609+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=7843) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-21T04:52:55.610+0000] {standard_task_runner.py:63} INFO - Started process 7845 to run task
[2024-05-21T04:52:55.610+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'push_to_s3', 'manual__2024-05-21T04:52:48.278946+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmph2jtkp__']
[2024-05-21T04:52:55.611+0000] {standard_task_runner.py:91} INFO - Job 69: Subtask push_to_s3
[2024-05-21T04:52:55.631+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.push_to_s3 manual__2024-05-21T04:52:48.278946+00:00 [running]> on host 39024998a807
[2024-05-21T04:52:55.669+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='push_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T04:52:48.278946+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-21T04:52:48.278946+00:00'
[2024-05-21T04:52:55.670+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-21T04:52:55.674+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-21T04:52:55.675+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather_dag.py", line 12, in pushS3
    client = boto3.client('s3', aws_access_key=ACCESS_KEY, aws_secret_access_key=SECRET_KEY)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/boto3/__init__.py", line 92, in client
    return _get_default_session().client(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Session.client() got an unexpected keyword argument 'aws_access_key'
[2024-05-21T04:52:55.679+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag, task_id=push_to_s3, run_id=manual__2024-05-21T04:52:48.278946+00:00, execution_date=20240521T045248, start_date=20240521T045255, end_date=20240521T045255
[2024-05-21T04:52:55.684+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 69 for task push_to_s3 (Session.client() got an unexpected keyword argument 'aws_access_key'; 7845)
[2024-05-21T04:52:55.709+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-21T04:52:55.718+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-21T04:52:55.719+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
