[2024-05-21T04:04:00.780+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-21T04:04:00.787+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data manual__2024-05-21T04:03:54.140486+00:00 [queued]>
[2024-05-21T04:04:00.791+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data manual__2024-05-21T04:03:54.140486+00:00 [queued]>
[2024-05-21T04:04:00.792+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-05-21T04:04:00.798+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_load_weather_data> on 2024-05-21 04:03:54.140486+00:00
[2024-05-21T04:04:00.803+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=7222) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-21T04:04:00.804+0000] {standard_task_runner.py:63} INFO - Started process 7224 to run task
[2024-05-21T04:04:00.804+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'transform_load_weather_data', 'manual__2024-05-21T04:03:54.140486+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp1fku6cl8']
[2024-05-21T04:04:00.805+0000] {standard_task_runner.py:91} INFO - Job 58: Subtask transform_load_weather_data
[2024-05-21T04:04:00.831+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.transform_load_weather_data manual__2024-05-21T04:03:54.140486+00:00 [running]> on host 39024998a807
[2024-05-21T04:04:00.873+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='transform_load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T04:03:54.140486+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-21T04:03:54.140486+00:00'
[2024-05-21T04:04:00.874+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-21T04:04:00.888+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-21T04:04:00.889+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/fsspec/registry.py", line 236, in get_filesystem_class
    register_implementation(protocol, _import_class(bit["class"]))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/fsspec/registry.py", line 271, in _import_class
    mod = importlib.import_module(mod)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 's3fs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather_dag.py", line 49, in transform_load_data
    df_data.to_csv(f"s3://weatherapiairflowproject-yml/{dt_string}.csv", index=False, storage_options=aws_credentials)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 718, in get_handle
    ioargs = _get_filepath_or_buffer(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 418, in _get_filepath_or_buffer
    file_obj = fsspec.open(
               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/fsspec/core.py", line 459, in open
    out = open_files(
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/fsspec/core.py", line 283, in open_files
    fs, fs_token, paths = get_fs_token_paths(
                          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/fsspec/core.py", line 623, in get_fs_token_paths
    chain = _un_chain(urlpath0, storage_options or {})
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/fsspec/core.py", line 332, in _un_chain
    cls = get_filesystem_class(protocol)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/fsspec/registry.py", line 238, in get_filesystem_class
    raise ImportError(bit["err"]) from e
ImportError: Install s3fs to access S3
[2024-05-21T04:04:00.899+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag, task_id=transform_load_weather_data, run_id=manual__2024-05-21T04:03:54.140486+00:00, execution_date=20240521T040354, start_date=20240521T040400, end_date=20240521T040400
[2024-05-21T04:04:00.908+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 58 for task transform_load_weather_data (Install s3fs to access S3; 7224)
[2024-05-21T04:04:00.943+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-21T04:04:00.951+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-21T04:04:00.952+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
