[2024-05-21T17:09:12.486+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-21T17:09:12.493+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data manual__2024-05-21T17:09:07.107583+00:00 [queued]>
[2024-05-21T17:09:12.496+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data manual__2024-05-21T17:09:07.107583+00:00 [queued]>
[2024-05-21T17:09:12.496+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-05-21T17:09:12.502+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_load_weather_data> on 2024-05-21 17:09:07.107583+00:00
[2024-05-21T17:09:12.506+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=10180) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-21T17:09:12.507+0000] {standard_task_runner.py:63} INFO - Started process 10182 to run task
[2024-05-21T17:09:12.507+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'transform_load_weather_data', 'manual__2024-05-21T17:09:07.107583+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp1iow81q6']
[2024-05-21T17:09:12.508+0000] {standard_task_runner.py:91} INFO - Job 120: Subtask transform_load_weather_data
[2024-05-21T17:09:12.529+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.transform_load_weather_data manual__2024-05-21T17:09:07.107583+00:00 [running]> on host 39024998a807
[2024-05-21T17:09:12.570+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='transform_load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T17:09:07.107583+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-21T17:09:07.107583+00:00'
[2024-05-21T17:09:12.571+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-21T17:09:12.655+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-21T17:09:12.656+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather_dag.py", line 78, in transform_load_data
    client.put_object(Bucket=bucket_name, Key=dt_string, Body=csv_writer.getvalue())
                                                              ^^^^^^^^^^^^^^^^^^^
AttributeError: '_csv.writer' object has no attribute 'getvalue'
[2024-05-21T17:09:12.663+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_dag, task_id=transform_load_weather_data, run_id=manual__2024-05-21T17:09:07.107583+00:00, execution_date=20240521T170907, start_date=20240521T170912, end_date=20240521T170912
[2024-05-21T17:09:12.669+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 120 for task transform_load_weather_data ('_csv.writer' object has no attribute 'getvalue'; 10182)
[2024-05-21T17:09:12.688+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-21T17:09:12.697+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-21T17:09:12.697+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
