[2024-05-21T05:02:20.329+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-21T05:02:20.338+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.push_to_s3 manual__2024-05-21T04:58:10.374992+00:00 [queued]>
[2024-05-21T05:02:20.341+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.push_to_s3 manual__2024-05-21T04:58:10.374992+00:00 [queued]>
[2024-05-21T05:02:20.342+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-05-21T05:02:20.348+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): push_to_s3> on 2024-05-21 04:58:10.374992+00:00
[2024-05-21T05:02:20.351+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=8009) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-21T05:02:20.352+0000] {standard_task_runner.py:63} INFO - Started process 8011 to run task
[2024-05-21T05:02:20.353+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'push_to_s3', 'manual__2024-05-21T04:58:10.374992+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpb_xhpmdg']
[2024-05-21T05:02:20.354+0000] {standard_task_runner.py:91} INFO - Job 83: Subtask push_to_s3
[2024-05-21T05:02:20.379+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.push_to_s3 manual__2024-05-21T04:58:10.374992+00:00 [running]> on host 39024998a807
[2024-05-21T05:02:20.422+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='push_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T04:58:10.374992+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-21T04:58:10.374992+00:00'
[2024-05-21T05:02:20.423+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-21T05:02:20.491+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-21T05:02:20.492+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather_dag.py", line 13, in pushS3
    client.upload_fileobj("weatherapiairflowproject-yml","/opt/airflow/logs/{dt_string}.csv")
TypeError: upload_fileobj() missing 1 required positional argument: 'Key'
[2024-05-21T05:02:20.497+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=weather_dag, task_id=push_to_s3, run_id=manual__2024-05-21T04:58:10.374992+00:00, execution_date=20240521T045810, start_date=20240521T050220, end_date=20240521T050220
[2024-05-21T05:02:20.503+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 83 for task push_to_s3 (upload_fileobj() missing 1 required positional argument: 'Key'; 8011)
[2024-05-21T05:02:20.538+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-21T05:02:20.547+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-21T05:02:20.548+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
